List<String> educationCourses = [
  "Computer Science",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Engineering",
  "Psychology",
  "Economics",
  "History",
  "Literature",
  "Art History",
  "Political Science",
  "Sociology",
  "Philosophy",
  "Business Administration",
  "Medicine",
  "Nursing",
  "Dentistry",
  "Law",
  "Architecture",
  "Education",
  "Environmental Science",
  "Agriculture",
  "Hospitality Management",
  "Culinary Arts",
  "Fashion Design",
  "Music",
  "Film Studies",
  "Journalism",
  "Languages",
  "Graphic Design",
  "Public Health",
  "International Relations",
  "Anthropology",
  "Geography",
  "Religious Studies",
  "Aviation",
  "Marine Biology",
  "Urban Planning",
  "Drama/Theater",
  "Physical Education",
  "Library Science",
  "Forensic Science",
  "Fire Science",
  "Veterinary Medicine",
  "Cybersecurity",
  "Data Science",
  "Robotics",
  "Biomedical Engineering",
  "Game Design",
  "Ethical Hacking",
  "Renewable Energy",
  "Space Exploration",
  "Actuarial Science",
  "Fashion Merchandising",
  "Interior Design",
  "Event Planning",
  "Sports Management",
  "Animation",
  "Healthcare Administration",
  "Criminal Justice",
  "Emergency Management",
  "Public Administration",
  "Real Estate",
  "Social Work",
  "Teaching English as a Second Language (TESL)",
  "Early Childhood Education",
  "Special Education",
  "Music Therapy",
  "Nutrition",
  "Physical Therapy",
  "Occupational Therapy",
  "Speech Therapy",
  "Exercise Physiology",
  "Wildlife Conservation",
  "Zoology",
  "Paleontology",
  "Linguistics",
  "Archaeology",
  "Astronomy",
  "Meteorology",
  "Oceanography",
  "Sustainability Studies",
  "Quantum Mechanics",
  "Artificial Intelligence",
  "Machine Learning",
  "Ethics",
  "Leadership",
  "Personal Development",
  "Entrepreneurship",
  "Finance",
  "Marketing",
  "Human Resources Management",
  "Supply Chain Management",
  "Project Management",
  "Quality Management",
  "Risk Management",
  "Strategic Management",
  "Digital Marketing",
  "Content Marketing",
  "Social Media Marketing",
  "Search Engine Optimization (SEO)",
  "Financial Planning",
  "Investment Management",
  "Behavioral Economics",
  "Game Theory",
  "Microeconomics",
  "Macroeconomics",
  "Organizational Psychology",
  "Cognitive Psychology",
  "Developmental Psychology",
  "Clinical Psychology",
  "Health Psychology",
  "Sports Psychology",
  "Positive Psychology",
  "Educational Psychology",
  "Environmental Psychology",
  "Industrial-Organizational Psychology",
  "Neuropsychology",
  "Counseling Psychology",
  "Quantitative Psychology",
  "Social Psychology",
  "Music Psychology",
  "Political Psychology",
  "Military Psychology",
  "Consumer Psychology",
  "Forensic Psychology",
  "Community Psychology",
  "Aviation Psychology",
  "Cyberpsychology",
  "Space Psychology",
  "Religious Psychology",
  "Art Therapy",
  "Dance Therapy",
  "Drama Therapy",
  "Play Therapy",
  "Animal-Assisted Therapy",
  "Expressive Therapy",
  "Mindfulness-Based Therapy",
  "Family Therapy",
  "Couples Therapy",
  "Group Therapy",
  "Cognitive-Behavioral Therapy (CBT)",
  "Psychodynamic Therapy",
  "Humanistic Therapy",
  "Existential Therapy",
  "Solution-Focused Brief Therapy (SFBT)",
  "Gestalt Therapy",
  "Narrative Therapy",
  "Emotion-Focused Therapy (EFT)",
  "Schema Therapy",
  "Trauma Therapy",
  "Artificial Intelligence Ethics",
  "Business Ethics",
  "Medical Ethics",
  "Engineering Ethics",
  "Journalism Ethics",
  "Environmental Ethics",
  "Bioethics",
  "Cyber Ethics",
  "Legal Ethics",
  "Research Ethics",
  "Corporate Governance",
  "Sustainable Business Practices",
  "International Business",
  "Cross-Cultural Communication",
  "Technical Writing",
  "Creative Writing",
  "Screenwriting",
  "Poetry",
  "Fiction Writing",
  "Nonfiction Writing",
  "Scriptwriting",
  "Copywriting",
  "Grant Writing",
  "Editing and Proofreading",
  "Journalism Ethics",
  "News Reporting",
  "Broadcast Journalism",
  "Photojournalism",
  "Investigative Journalism",
  "Sports Journalism",
  "Science Journalism",
  "Health Journalism",
  "Fashion Journalism",
  "Travel Journalism",
  "Music Journalism",
  "Entertainment Journalism",
  "Political Journalism",
  "Opinion Journalism",
  "Literary Journalism",
  "Feature Writing",
  "Magazine Writing",
  "Newspaper Writing",
  "Web Content Writing",
  "Social Media Writing",
  "Technical Writing",
  "Grant Writing",
  "Proposal Writing",
  "White Paper Writing",
  "Instructional Design",
  "E-Learning Development",
  "Curriculum Design",
  "Educational Technology",
  "Online Teaching",
  "Blended Learning",
  "Instructional Coaching",
  "Assessment and Evaluation",
  "Learning Analytics",
  "Educational Leadership",
  "School Administration",
  "Student Affairs",
  "Higher Education Administration",
  "Education Policy",
  "Education Law",
  "Global Education",
  "Multicultural Education",
  "Gender and Education",
  "STEM Education",
  "STEAM Education",
  "Environmental Education",
  "Outdoor Education",
  "Experiential Education",
  "Service-Learning",
  "Social-Emotional Learning (SEL)",
  "Character Education",
  "Homeschooling",
  "Montessori Education",
  "Waldorf Education",
  "Reggio Emilia Approach",
  "Project-Based Learning",
  "Problem-Based Learning",
  "Inquiry-Based Learning",
  "Cooperative Learning",
  "Collaborative Learning",
  "Critical Pedagogy",
  "Place-Based Education",
  "Global Citizenship Education",
  "Civic Education",
  "Media Literacy Education",
  "Financial Literacy Education",
  "Digital Literacy Education",
  "Health Literacy Education",
  "STEM Literacy Education",
  "Cultural Literacy Education",
  "Visual Arts Education",
  "Music Education",
  "Drama Education",
  "Dance Education",
  "Physical Education",
  "Health Education",
  "Nutrition Education",
  "Sex Education",
  "Drug Education",
  "Alcohol Education",
  "Tobacco Education",
  "Mental Health Education",
  "Special Education",
  "Inclusive Education",
  "Gifted Education",
  "Talented Education",
  "Early Childhood Education",
  "Elementary Education",
  "Middle School Education",
  "Secondary Education",
  "High School Education",
  "College Education",
  "University Education",
  "Vocational Education",
  "Technical Education",
  "Professional Development",
  "Adult Education",
  "Continuing Education",
  "Online Education",
  "Distance Education",
  "MOOCs (Massive Open Online Courses)",
  "Microlearning",
  "Self-Directed Learning",
  "Personalized Learning",
  "Competency-Based Learning",
  "Adaptive Learning",
  "Flipped Classroom",
  "Gamification in Education",
  "Virtual Reality in Education",
  "Augmented Reality in Education",
  "Artificial Intelligence in Education",
  "Robotics in Education",
  "Mobile Learning",
  "Social Learning",
  "Collaborative Learning",
  "Peer Learning",
  "Problem-Based Learning",
  "Project-Based Learning",
  "Experiential Learning",
  "Service Learning",
  "Internships",
  "Apprenticeships",
  "Field Studies",
  "Study Abroad Programs",
  "Educational Tours",
  "Educational Games",
  "Educational Apps",
  "Educational Videos",
  "Educational Podcasts",
  "Educational Websites",
  "Educational Blogs",
  "Educational Webinars",
  "Educational Conferences",
  "Educational Seminars",
  "Educational Workshops",
  "Professional Development Programs",
  "Teacher Training Programs",
  "Staff Development Programs",
  "Leadership Development Programs",
  "Online Courses",
  "Certification Programs",
  "Diploma Programs",
  "Associate's Degree Programs",
  "Bachelor's Degree Programs",
  "Master's Degree Programs",
  "Doctoral Degree Programs",
  "Ph.D. Programs",
  "Ed.D. Programs",
  "MBA Programs",
  "JD Programs",
  "MD Programs",
  "DDS Programs",
  "DVM Programs",
  "PharmD Programs",
  "PsyD Programs",
  "MSW Programs",
  "MPH Programs",
  "MFA Programs",
  "MEd Programs",
  "MA Programs",
  "MSc Programs",
  "MT Programs",
  "MPT Programs",
  "OTD Programs",
  "AuD Programs",
  "CRNA Programs",
  "PA Programs",
  "BSN Programs",
  "RN Programs",
  "LPN Programs",
  "ADN Programs",
  "LVN Programs",
  "CNA Programs",
  "EMT Programs",
  "Paramedic Programs",
  "Surgical Tech Programs",
  "Radiology Tech Programs",
  "Phlebotomy Tech Programs",
  "Medical Assistant Programs",
  "Dental Assistant Programs",
  "Pharmacy Tech Programs",
  "Physical Therapy Assistant Programs",
  "Occupational Therapy Assistant Programs",
  "Veterinary Assistant Programs",
  "Cosmetology Programs",
  "Barbering Programs",
  "Esthetics Programs",
  "Nail Tech Programs",
  "Massage Therapy Programs",
  "Holistic Health Programs",
  "Yoga Teacher Training Programs",
  "Personal Trainer Certification Programs",
  "Nutrition Coach Certification Programs",
  "Pilates Instructor Certification Programs",
  "Life Coach Certification Programs",
  "Counseling Certification Programs",
  "Addiction Counselor Certification Programs",
  "Art Therapy Certification Programs",
  "Music Therapy Certification Programs",
  "Dance/Movement Therapy Certification Programs",
  "Drama Therapy Certification Programs",
  "Play Therapy Certification Programs",
  "Animal-Assisted Therapy Certification Programs",
  "Expressive Therapy Certification Programs",
  "Mindfulness-Based Therapy Certification Programs",
  "Family Therapy Certification Programs",
  "Couples Therapy Certification Programs",
  "Group Therapy Certification Programs",
  "Cognitive-Behavioral Therapy (CBT) Certification Programs",
  "Psychodynamic Therapy Certification Programs",
  "Humanistic Therapy Certification Programs",
  "Existential Therapy Certification Programs",
  "Solution-Focused Brief Therapy (SFBT) Certification Programs",
  "Gestalt Therapy Certification Programs",
  "Narrative Therapy Certification Programs",
  "Emotion-Focused Therapy (EFT) Certification Programs",
  "Schema Therapy Certification Programs",
  "Trauma Therapy Certification Programs",
  "Child and Adolescent Therapy Certification Programs",
  "Art Therapy Supervision Certification Programs",
  "Dance/Movement Therapy Supervision Certification Programs",
  "Drama Therapy Supervision Certification Programs",
  "Play Therapy Supervision Certification Programs",
  "Animal-Assisted Therapy Supervision Certification Programs",
  "Expressive Therapy Supervision Certification Programs",
  "Mindfulness-Based Therapy Supervision Certification Programs",
  "Family Therapy Supervision Certification Programs",
  "Couples Therapy Supervision Certification Programs",
  "Group Therapy Supervision Certification Programs",
  "Cognitive-Behavioral Therapy (CBT) Supervision Certification Programs",
  "Psychodynamic Therapy Supervision Certification Programs",
  "Humanistic Therapy Supervision Certification Programs",
  "Existential Therapy Supervision Certification Programs",
  "Solution-Focused Brief Therapy (SFBT) Supervision Certification Programs",
  "Gestalt Therapy Supervision Certification Programs",
  "Narrative Therapy Supervision Certification Programs",
  "Emotion-Focused Therapy (EFT) Supervision Certification Programs",
  "Schema Therapy Supervision Certification Programs",
  "Trauma Therapy Supervision Certification Programs",
  "Child and Adolescent Therapy Supervision Certification Programs",
  "Art Therapy Continuing Education Programs",
  "Dance/Movement Therapy Continuing Education Programs",
  "Drama Therapy Continuing Education Programs",
  "Play Therapy Continuing Education Programs",
  "Animal-Assisted Therapy Continuing Education Programs",
  "Expressive Therapy Continuing Education Programs",
  "Mindfulness-Based Therapy Continuing Education Programs",
  "Family Therapy Continuing Education Programs",
  "Couples Therapy Continuing Education Programs",
  "Group Therapy Continuing Education Programs",
  "Cognitive-Behavioral Therapy (CBT) Continuing Education Programs",
  "Psychodynamic Therapy Continuing Education Programs",
  "Humanistic Therapy Continuing Education Programs",
  "Existential Therapy Continuing Education Programs",
  "Solution-Focused Brief Therapy (SFBT) Continuing Education Programs",
  "Gestalt Therapy Continuing Education Programs",
  "Narrative Therapy Continuing Education Programs",
  "Emotion-Focused Therapy (EFT) Continuing Education Programs",
  "Schema Therapy Continuing Education Programs",
  "Trauma Therapy Continuing Education Programs",
  "Child and Adolescent Therapy Continuing Education Programs",
  "Art Therapy Licensure Programs",
  "Dance/Movement Therapy Licensure Programs",
  "Drama Therapy Licensure Programs",
  "Play Therapy Licensure Programs",
  "Animal-Assisted Therapy Licensure Programs",
  "Expressive Therapy Licensure Programs",
  "Mindfulness-Based Therapy Licensure Programs",
  "Family Therapy Licensure Programs",
  "Couples Therapy Licensure Programs",
  "Group Therapy Licensure Programs",
  "Cognitive-Behavioral Therapy (CBT) Licensure Programs",
  "Psychodynamic Therapy Licensure Programs",
  "Humanistic Therapy Licensure Programs",
  "Existential Therapy Licensure Programs",
  "Solution-Focused Brief Therapy (SFBT) Licensure Programs",
  "Gestalt Therapy Licensure Programs",
  "Narrative Therapy Licensure Programs",
  "Emotion-Focused Therapy (EFT) Licensure Programs",
  "Schema Therapy Licensure Programs",
  "Trauma Therapy Licensure Programs",
  "Child and Adolescent Therapy Licensure Programs",
  "Art Therapy Internship Programs",
  "Dance/Movement Therapy Internship Programs",
  "Drama Therapy Internship Programs",
  "Play Therapy Internship Programs",
  "Animal-Assisted Therapy Internship Programs",
  "Expressive Therapy Internship Programs",
  "Mindfulness-Based Therapy Internship Programs",
  "Family Therapy Internship Programs",
  "Couples Therapy Internship Programs",
  "Group Therapy Internship Programs",
  "Cognitive-Behavioral Therapy (CBT) Internship Programs",
  "Psychodynamic Therapy Internship Programs",
  "Humanistic Therapy Internship Programs",
  "Existential Therapy Internship Programs",
  "Solution-Focused Brief Therapy (SFBT) Internship Programs",
  "Gestalt Therapy Internship Programs",
  "Narrative Therapy Internship Programs",
  "Emotion-Focused Therapy (EFT) Internship Programs",
  "Schema Therapy Internship Programs",
  "Trauma Therapy Internship Programs",
  "Child and Adolescent Therapy Internship Programs",
];
